# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='image',
            new_name='uploaded_file',
        ),
    ]
