# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20180622_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='uploaded_file',
            field=models.FileField(upload_to='images/'),
        ),
    ]
